name: citytaxi1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  image_picker: ^1.1.2
  google_maps_flutter: ^2.9.0 # For mobile
  google_maps_webservice: ^0.0.20-nullsafety.5 # Downgraded to a compatible version
  location: ^6.0.2
  geolocator: ^8.2.1
  url_launcher: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/logo.png
    - assets/A.png
    - assets/A1.png
    - assets/B.png
    - assets/B1.png
    - assets/C.png
    - assets/C1.png
    - assets/CE.png
    - assets/D.png
    - assets/D1.png
    - assets/DE.png
    - assets/G.png
    - assets/G1.png
    - assets/J.png

  uses-material-design: true

  
